# https://travis-ci.org/denisidoro/navi
language: rust

jobs:
  include:

  - name: run tests
    rust: stable
    script:
    - cargo test --all --locked
    - rustup component add rustfmt-preview
    - cargo fmt --all -- --check
    env: RUST_BACKTRACE=1

  - name: build binary on ubuntu
    rust: stable
    script: cargo build --release --locked

  - name: build binary for x86_64-unknown-linux-musl
    rust: stable
    script:
      - cargo install cross
      - cross build --release --locked --target x86_64-unknown-linux-musl

  - name: build binary for aarch64-linux-android
    rust: stable
    script:
      - cargo install cross
      - cross build --release --locked --target aarch64-linux-android

  - name: build binary for armv7-linux-androideabi
    rust: stable
    script:
      - cargo install cross
      - cross build --release --locked --target armv7-linux-androideabi

  - name: build binary for armv7-unknown-linux-musleabihf
    rust: stable
    script:
      - cargo install cross
      - cross build --release --locked --target armv7-unknown-linux-musleabihf

  - name: build binary on osx
    os: osx
    rust: stable
    script: cargo build --release --locked

notifications:
  irc:
    on_failure: always
    channels:
      - "irc.freenode.net#navi"
    template:
      - "%{result} - %{repository_slug} %{branch} \"%{commit_subject}\" %{build_url}"
