on:
  push:

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Prep environment to test compiled-in paths
        run: |
          mkdir /tmp/cheats-dir
          touch /tmp/config-file

      - name: Run cargo test
        run: cargo test
        env:
          NAVI_PATH: /tmp/cheats-dir
          NAVI_CONFIG: /tmp/config-file

      - name: Run cargo test (default paths)
        run: cargo test

      - name: Install deps
        run: ./scripts/dot pkg add git bash npm tmux

      - name: Install fzf
        run: git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf; yes | ~/.fzf/install;

      - name: Add fzf to PATH
        run: echo "$HOME/.fzf/bin" >> "$GITHUB_PATH"

      - name: Install tealdeer
        run: sudo npm install -g tldr

      - name: Run bash tests
        run: ./tests/run

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
