on:
  push:

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Run cargo test
        run: cargo test

      - name: Run cargo build
        run: cargo build

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git bash tmux

      - name: Install fzf
        run: git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf; yes | ~/.fzf/install;

      - name: Add fzf to PATH
        run: echo "$HOME/.fzf/bin" >> "$GITHUB_PATH"

      - name: Install tealdeer
        run: sudo npm install -g tldr

      - name: Run bash tests
        run: ./tests/run.sh

  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
